version: '3'
services:
  app:
    build: .
    ports:
      - "5001:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: